- hosts: localhost
  become: yes

  tasks:
    - name: Pull latest Docker image
      command: docker pull abhishekkhond/scientific-calculator

    - name: Stop existing container (if running)
      command: docker stop scientific-calculator
      ignore_errors: yes

    - name: Remove old container (if any)
      command: docker rm scientific-calculator
      ignore_errors: yes

    - name: Run new container
      command: docker run -itd --name scientific-calculator abhishekkhond/scientific-calculator

    - name: Show running containers
      command: docker ps
      register: container_output

    - name: Print container status
      debug:
        var: container_output.stdout